!$THEME = "elegant"

'' Theme palette

!global $THEME_PALETTE_PRIMARY_LIGHTER = "#FFFFFF"
!global $THEME_PALETTE_PRIMARY_LIGHT   = "#FAFAFA"
!global $THEME_PALETTE_PRIMARY        = "#EAEAEA"
!global $THEME_PALETTE_PRIMARY_DARK    = "#999999"
!global $THEME_PALETTE_PRIMARY_DARKER  = "#404344"

!global $THEME_PALETTE_ACCENT_LIGHTER  = "#709499"
!global $THEME_PALETTE_ACCENT_LIGHT    = "#6C7778"
!global $THEME_PALETTE_ACCENT         = "#3D6067"
!global $THEME_PALETTE_ACCENT_DARK     = "#012E37"
!global $THEME_PALETTE_ACCENT_DARKER   = "#001E26"

'' Basic colors

!global $THEME_COLOR_ARROW = $THEME_PALETTE_PRIMARY_DARK
!global $THEME_COLOR_TEXT = $THEME_PALETTE_PRIMARY_DARKER
!global $THEME_COLOR_BACKGROUND = $THEME_PALETTE_PRIMARY
!global $THEME_COLOR_CONTAINER_BACKGROUND = $THEME_PALE_TTE_PRIMARY_LIGHT
!global $THEME_COLOR_BORDER = $THEME_PALETTE_PRIMARY_DARK
!global $THEME_COLOR_NOTE = "#FEFFC2"
!global $THEME_COLOR_ABSTRACT = "#87BBA2"
!global $THEME_COLOR_DATA = "#75B9C6"
!global $THEME_COLOR_CLASS = "#E76F51"
!global $THEME_COLOR_ENUM = "#B49DC0"
!global $THEME_COLOR_INTERFACE = "#E9C46A"
!global $THEME_COLOR_ANNOTATION = "#FFB06A"

'' Text

!$THEME_TEXT_FONT = "Amazon Ember"
!$THEME_TEXT_FONT_MONO = "Monospaced"

!$THEME_TEXT_SIZE_TITLE = 18
!$THEME_TEXT_SIZE_HEADER = 10
!$THEME_TEXT_SIZE_FOOTER = 10
!$THEME_TEXT_SIZE_GROUP_NAME = 14
!$THEME_TEXT_SIZE_ELEMENT_NAME = 14
!$THEME_TEXT_SIZE_ATTRIBUTES = 13
!$THEME_TEXT_SIZE_NOTES = 13
!$THEME_TEXT_SIZE_ARROW_TEXT = 12
!$THEME_TEXT_SIZE_SEQUENCE_GROUPS = 12
!$THEME_TEXT_SIZE_SEQUENCE_SEPARATORS = 11
!$THEME_TEXT_SIZE_STEREOTYPE = 11
!$THEME_TEXT_SIZE_ICON = 12


'' Procedures

!procedure $font_scheme($size=$THEME_TEXT_SIZE_GROUP_NAME, $style="normal", $family=$THEME_TEXT_FONT, $color=$THEME_COLOR_TEXT)
    FontName $family
    FontSize $size
    FontColor $color
    FontStyle $style
!endprocedure

!procedure $shape_scheme($bgColor=$THEME_COLOR_BACKGROUND, $color=$THEME_COLOR_BORDER, $thickness=1)
    BackgroundColor $bgColor
    BorderColor $color
    BorderThickness $thickness
!endprocedure

!procedure $borderless_shape_scheme($color, $thickness=1)
    $shape_scheme($color, $color, $thickness)
!endprocedure

!procedure $primary_scheme($bgColor=$THEME_COLOR_BACKGROUND, $color=$THEME_COLOR_BORDER, $thickness=1)
    $font_scheme()
    $shape_scheme()

    Stereotype {
        $font_scheme($THEME_TEXT_SIZE_STEREOTYPE)
    }
!endprocedure

!procedure $set_title($text)
title $text\n
!endprocedure

!procedure $set_legend($color1, $text1, $color2, $text2, $color3="", $text3="", $color4="", $text4="", $color5="", $text5="", $color6="", $text6="", $color7="", $text7="", $color8="", $text8="", $color9="", $text9="", $color10="", $text10="")
legend
    !local $legendText = "<color:" + $color1 + ">█</color> " + $text1
    !local $legendText = $legendText + " <color:" + $THEME_PALETTE_PRIMARY + ">|</color> <color:" + $color2 + ">█</color> " + $text2
    !if ($text3 != "") && ($color3 != "")
        !local $legendText = $legendText + " <color:" + $THEME_PALETTE_PRIMARY + ">|</color> <color:" + $color3 + ">█</color> " + $text3
    !endif
    !if ($text4 != "") && ($color4 != "")
        !local $legendText = $legendText + " <color:" + $THEME_PALETTE_PRIMARY + ">|</color> <color:" + $color4 + ">█</color> " + $text4
    !endif
    !if ($text5 != "") && ($color5 != "")
        !local $legendText = $legendText + " <color:" + $THEME_PALETTE_PRIMARY + ">|</color> <color:" + $color5 + ">█</color> " + $text5
    !endif
    !if ($text6 != "") && ($color6 != "")
        !local $legendText = $legendText + " <color:" + $THEME_PALETTE_PRIMARY + ">|</color> <color:" + $color6 + ">█</color> " + $text6
    !endif
    !if ($text7 != "") && ($color7 != "")
        !local $legendText = $legendText + " <color:" + $THEME_PALETTE_PRIMARY + ">|</color> <color:" + $color7 + ">█</color> " + $text7
    !endif
    !if ($text8 != "") && ($color8 != "")
        !local $legendText = $legendText + " <color:" + $THEME_PALETTE_PRIMARY + ">|</color> <color:" + $color8 + ">█</color> " + $text8
    !endif
    !if ($text9 != "") && ($color9 != "")
        !local $legendText = $legendText + " <color:" + $THEME_PALETTE_PRIMARY + ">|</color> <color:" + $color9 + ">█</color> " + $text9
    !endif
    !if ($text10 != "") && ($color10 != "")
        !local $legendText = $legendText + " <color:" + $THEME_PALETTE_PRIMARY + ">|</color> <color:" + $color10 + ">█</color> " + $text10
    !endif
    $legendText
end legend
!endprocedure

skinparam useBetaStyle false
skinparam shadowing false
skinparam componentStyle uml2
skinparam RoundCorner 4
skinparam wrapWidth 400
skinparam defaultTextAlignment left
skinparam backgroundColor $THEME_PALETTE_PRIMARY_LIGHTER

skinparam Note {
    $font_scheme($THEME_TEXT_SIZE_NOTES)
    $shape_scheme($THEME_COLOR_NOTE)
}

skinparam Legend {
    $shape_scheme($THEME_PALETTE_PRIMARY_LIGHT, $THEME_PALETTE_PRIMARY)
    $font_scheme()
}

skinparam Header {
    $font_scheme($THEME_TEXT_SIZE_HEADER, $family=$THEME_TEXT_FONT_MONO, $color=$THEME_PALETTE_PRIMARY_DARK)
}

skinparam Footer {
    $font_scheme($THEME_TEXT_SIZE_HEADER, $family=$THEME_TEXT_FONT_MONO, $color=$THEME_PALETTE_PRIMARY_DARK)
}

skinparam Arrow {
    Color $THEME_COLOR_ARROW
    $font_scheme($THEME_TEXT_SIZE_ARROW_TEXT)
}

skinparam Frame {
    $font_scheme()
    $shape_scheme($THEME_COLOR_CONTAINER_BACKGROUND)
}

skinparam Database {
    $font_scheme()
    $shape_scheme($THEME_COLOR_CONTAINER_BACKGROUND)
}

skinparam Rectangle {
    $font_scheme()
    $shape_scheme($THEME_COLOR_CONTAINER_BACKGROUND)
}

skinparam Package {
    $font_scheme()
    $shape_scheme($THEME_COLOR_CONTAINER_BACKGROUND)
}

skinparam Node {
    $font_scheme()
    $shape_scheme($THEME_COLOR_CONTAINER_BACKGROUND)
}

skinparam Cloud {
    $font_scheme()
    $shape_scheme($THEME_COLOR_CONTAINER_BACKGROUND)
}

skinparam CircledCharacter {
    $font_scheme($THEME_TEXT_SIZE_ICON, "bold", $THEME_TEXT_FONT_MONO)
    Radius 10
}

skinparam SpotChar<<data>> D
skinparam Stereotype {
    A {
        $borderless_shape_scheme($THEME_COLOR_ABSTRACT)
    }

    C<<data>> {
        $borderless_shape_scheme($THEME_COLOR_DATA)
    }

    C {
        $borderless_shape_scheme($THEME_COLOR_CLASS)
    }

    E {
        $borderless_shape_scheme($THEME_COLOR_ENUM)
    }

    I {
        $borderless_shape_scheme($THEME_COLOR_INTERFACE)
    }

    N {
        $borderless_shape_scheme($THEME_COLOR_ANNOTATION)
    }
}

skinparam Actor {
    $primary_scheme()
}

skinparam Card {
    $primary_scheme()
}

skinparam Component {
    $primary_scheme()
}

skinparam Boundary {
    $primary_scheme()
}

skinparam Artifact {
    $primary_scheme()
}

skinparam File {
    $primary_scheme()
}

skinparam Interface {
    $primary_scheme()
}

skinparam Class {
    $primary_scheme()

    Attribute {
        $font_scheme($THEME_TEXT_SIZE_ATTRIBUTES)
    }
}

skinparam Object {
    $primary_scheme()

    Attribute {
        $font_scheme($THEME_TEXT_SIZE_ATTRIBUTES)
    }
}

skinparam Activity {
    $font_scheme()
    $shape_scheme()

    Diamond {
        $font_scheme()
        $shape_scheme()
    }

    BarColor $THEME_COLOR_ARROW
    EndColor $THEME_COLOR_ARROW
    StartColor $THEME_COLOR_ARROW
}

skinparam Sequence {
    Box {
        $primary_scheme()
    }

    Delay {
        $font_scheme($THEME_TEXT_SIZE_SEQUENCE_SEPARATORS)
    }

    LifeLine {
        $primary_scheme()
    }

    Participant {
        $primary_scheme()
    }
}

skinparam Usecase {
    $primary_scheme()
}

hide <<data>> stereotype
hide empty methods
hide empty fields

!if %variable_exists("COPYRIGHT_OWNER")
    header %upper(COPYRIGHT_OWNER) CONFIDENTIAL\n
    center footer \nCopyright © %date("yyyy"). COPYRIGHT_OWNER, Inc. or its affiliates. All Rights Reserved
!endif
